### PR TITLE
require controller in FilterForm

### PR DESCRIPTION
**Pull request by mmoll**
@periklis @calbrecht @ritters @elger @andythedandy @danielhallmann please review.

### CODE REVIEW

**Comment by calbrecht** [comment]
:+1:

**Comment by andythedandy** [comment]
Works. Thx.

**Comment by ritters** [comment]
top

**Comment by mmoll** [comment]
sänk ju änd servus

**Comment by mmoll** [comment]
I rebased filter_fixes onto current master and force pushed. Please update your local repos.

**Pull request merged**
