### PR TITLE
add form filter item ordering

### LINKED ISSUE #9: custom ordering of items in filter form

### PR DESCRIPTION
**Pull request by xalopp**
closes GH-9

### CODE REVIEW

**Comment by xalopp** [comment]
@ritters @mmoll @andythedandy @danielhallmann @elger @periklis @calbrecht @ma27 @aoldemeier  could you have a look at this PR?

**Comment by mmoll** [comment]
I'm highly fond of this PR :green_heart:

**Comment by mmoll** [comment]
@codec icanhaz man team membership? kthxbai

**Comment by andythedandy** [comment]
Great! :purple_heart:

**Pull request merged**
